# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-26 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('succeeded', 'succeeded'), ('failed', 'failed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.TextField()),
                ('keywords', models.TextField()),
                ('is_regex', models.BooleanField(default=False)),
                ('results', models.IntegerField(null=True)),
            ],
        ),
    ]
