# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-19 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20170219_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='arguments',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='results',
            field=models.IntegerField(null=True),
        ),
    ]
